// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYYSorbIj1LmEUoxt089IA739Usiv65nA',
    appId: '1:243049327951:web:1fe7bb3988b0dcda4b693a',
    messagingSenderId: '243049327951',
    projectId: 'kick-off-1',
    authDomain: 'kick-off-1.firebaseapp.com',
    storageBucket: 'kick-off-1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASAE-DK_DhpRBg9yNBBS1_dg4LpL5GOJI',
    appId: '1:243049327951:android:aa8e3b75ceefa3e74b693a',
    messagingSenderId: '243049327951',
    projectId: 'kick-off-1',
    storageBucket: 'kick-off-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGKbi9CmvPaOFZCLSiJTEDHNZc3UK7HgM',
    appId: '1:243049327951:ios:86a46ab603680b704b693a',
    messagingSenderId: '243049327951',
    projectId: 'kick-off-1',
    storageBucket: 'kick-off-1.firebasestorage.app',
    iosClientId: '243049327951-021j2aorar2g5bq0lub6k5fuld3uhgjj.apps.googleusercontent.com',
    iosBundleId: 'com.example.kickoff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGKbi9CmvPaOFZCLSiJTEDHNZc3UK7HgM',
    appId: '1:243049327951:ios:86a46ab603680b704b693a',
    messagingSenderId: '243049327951',
    projectId: 'kick-off-1',
    storageBucket: 'kick-off-1.firebasestorage.app',
    iosClientId: '243049327951-021j2aorar2g5bq0lub6k5fuld3uhgjj.apps.googleusercontent.com',
    iosBundleId: 'com.example.kickoff',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYYSorbIj1LmEUoxt089IA739Usiv65nA',
    appId: '1:243049327951:web:91e9eb83c0b19a0b4b693a',
    messagingSenderId: '243049327951',
    projectId: 'kick-off-1',
    authDomain: 'kick-off-1.firebaseapp.com',
    storageBucket: 'kick-off-1.firebasestorage.app',
  );

}